### ISSUE TITLE
Add track description

### ISSUE THREAD

**Issue by angelk** [trackhub/website#168]
There should be (short) track description.
We may add bbcode the the text.

**Comment by StefanMavrodiev** [comment]
When you're saying bbcode, which functions do you mean?

**Comment by angelk** [comment]
We may use https://github.com/angelk/bbCode/blob/master/README.md

**Comment by StefanMavrodiev** [comment]
Or maybe some js/react text editor?

**Comment by angelk** [comment]
wysiwyg editor?
