### ISSUE TITLE
Upgrade to symfony 5.0

### ISSUE THREAD

**Issue by angelk** [trackhub/website#175]
See https://github.com/trackhub/website/issues/174

**Comment by StefanMavrodiev** [comment]
If we move to symfony 5, we cannot use FOSUserBundle as it's no longer supported.
 Maybe we should drop it, as suggested [here](https://jolicode.github.io/fosuserbundle-conf/#/)?

**Comment by angelk** [comment]
yes, it is ok to drop it

**Comment by angelk** [comment]
See https://github.com/trackhub/website/pull/274
