### ISSUE TITLE
Create project for the API

### ISSUE THREAD

**Issue by angelk** [trackhub/website#196]
We should remove the database connection from the `website` project and create new `api` project.
We should choose if we will use [REST](https://restfulapi.net/) or [GraphQL](https://graphql.org/learn/).
This will help with the mobile app integration.

My vote goes to graphQL

Ping @StefanMavrodiev 

Issues:

- [ ] Should we create separate endpoint for the track downloads (.gpx)
- [ ] Should we have separate project or endpoint for images uploads?
- [ ] Same for images serving
- [ ] login

**Comment by StefanMavrodiev** [comment]
> We should choose if we will use [REST](https://restfulapi.net/) or [GraphQL](https://graphql.org/learn/).
Best syntax ever. :)

> This will help with the mobile app integration.
Also we can go to SPA.

> My vote goes to graphQL
Same.

**Comment by StefanMavrodiev** [comment]
@angelk I've made some testing in #200.

However if the database + the GraphQL backend will be on a separate project, how the connection between the projects will be implemented? As a new virtual host in the apache configuration?

**Comment by angelk** [comment]
yes, new virtual host.
For example we may have `gaphql` hostname for the project.
In the beginning both graphql and website will be connected to the database from the website project.
Later the database will be moved to the graphQL project and database support will be dropped from the website project

**Comment by StefanMavrodiev** [comment]
@angelk Another question. The project will be in a separate container or as another project in the current?
I really like the idea separate container for each project. The downside is more initial work for maintaining the network connections.

**Comment by angelk** [comment]
The api will be in another project in separate container.

>The downside is more initial work for maintaining the network connections.

IMO its ok

**Comment by angelk** [comment]
Here are some issues:

Should we create separate endpoint for the track downloads (.gpx)
Should we have separate project or endpoint for images uploads?
Same for images serving

**Comment by angelk** [comment]
https://github.com/trackhub/api
