### ISSUE TITLE
Allow track variant rating

### ISSUE THREAD

**Issue by StefanMavrodiev** [trackhub/website#78]
Allow users to submit rating to track and/or track variant.

**Comment by angelk** [comment]
Additional ideas:
 "difficulties" like

- green
- blue
- black
- 2 x black

And statuses like:

- trail is ok
- trail have minor issues
- trail have some major issues ( a few fallen trees)
- trail is closed ( 10+ trees )

**Comment by StefanMavrodiev** [comment]
> Additional ideas:
> "difficulties" like
> 
>     * green
> 
>     * blue
> 
>     * black
> 
>     * 2 x black

@angelk 
Maybe using [this](https://www.imba.com/sites/default/files/content/resources/2018-10/IMBATrailDifficultRatingSystem.jpg?fbclid=IwAR3a1UqOLcJrJCGuE6l7791FCQJGbVlrVuOc4dlR7kEAwpq3fSqCMR1kc7k) as rating system?

**Comment by angelk** [comment]
@StefanMavrodiev yes, its perfect. Pinkbike uses the same system

**Comment by StefanMavrodiev** [comment]
Merged in #143
